# Generated by Django 5.2.1 on 2025-05-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h_order',
            old_name='transation_id',
            new_name='transaction_id',
        ),
    ]
