# Generated by Django 5.2.1 on 2025-05-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_g_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_product_gallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Product.d_product'),
        ),
    ]
