# Generated by Django 5.2.1 on 2025-06-07 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_h_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_order',
            name='order_uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
    ]
