# Generated by Django 5.2.1 on 2025-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_h_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_order',
            name='order_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
