# Generated by Django 5.2.1 on 2025-06-07 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_h_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
