# Generated by Django 5.2.1 on 2025-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_h_order_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='g_customer',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
